version: "3.7"
services:
  mqtt-broker1: &mqtt-broker
    image: eclipse-mosquitto:2.0
    volumes:
      - ./tests/config:/mosquitto/config
    ports:
      - 1883:1883
      - 9001:9001
#
#  mqtt-broker2:
#    <<: *mqtt-broker
#    ports:
#      - 1883:1883
#      - 9001:9001
  bridge:
    image: nimnull/mqtt-bridge:local
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mqtt-broker1
#      - mqtt-broker2
    links:
      - mqtt-broker1:mqtt-broker1
#      - mqtt-broker2:mqtt-broker2
    volumes:
#      - ./:/opt/srv
      - ./config.yaml:/opt/config.yaml
    ports:
      - "8080:8080"
